In [1]:
import numpy as np

In [2]:
# membuat sample array
arr = np.arange(0,11)

In [3]:
# show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# mendapatkan nilai pada index 7
arr[7]

7

In [6]:
# mendapatkan nilai pada range (1 hingga 5)
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
# bisa melakukan broadcasting
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
# membuat variabel baru untuk slicing
slice_of_arr = arr[5:10]
slice_of_arr

array([5, 6, 7, 8, 9])

In [11]:
# COPY ARRAY
arr_copy = arr.copy()
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])